{
 "title": "LOGS",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "ERRORS - LOGS",
   "type": "logs",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{level=\"ERROR\"}"
    }
   ]
  },
  {
   "title": "WARNS - LOGS",
   "type": "logs",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "{level=\"WARN\"}"
    }
   ]
  },
  {
   "title": "INFO - LOGS",
   "type": "logs",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "{level=\"INFO\"}"
    }
   ]
  }
 ]
}